# Generated by Django 6.0.2 on 2026-03-05 21:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myground', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AWSAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(help_text='12-digit AWS Account ID', max_length=12)),
                ('account_alias', models.CharField(blank=True, help_text='Friendly name for this account', max_length=100)),
                ('role_arn', models.CharField(help_text='ARN of the IAM role to assume, e.g. arn:aws:iam::123456789012:role/CostAnalyticsRole', max_length=2048)),
                ('external_id', models.CharField(default=uuid.uuid4, help_text='Unique external ID to prevent confused deputy attacks', max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('connected', 'Connected'), ('failed', 'Connection Failed'), ('disconnected', 'Disconnected')], default='pending', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aws_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'account_id')},
            },
        ),
        migrations.CreateModel(
            name='AWSCostAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=50)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('anomaly_date', models.DateField()),
                ('expected_cost', models.DecimalField(decimal_places=4, max_digits=10)),
                ('actual_cost', models.DecimalField(decimal_places=4, max_digits=10)),
                ('percent_increase', models.DecimalField(decimal_places=2, max_digits=6)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('aws_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='myground.awsaccount')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='AWSCostSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_cost', models.DecimalField(decimal_places=4, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('service_breakdown', models.JSONField(blank=True, default=dict)),
                ('tag_breakdown', models.JSONField(blank=True, default=dict)),
                ('daily_costs', models.JSONField(blank=True, default=list)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('aws_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_snapshots', to='myground.awsaccount')),
            ],
            options={
                'ordering': ['-period_start'],
                'unique_together': {('aws_account', 'period_start', 'period_end')},
            },
        ),
    ]
