# Generated by Django 6.0.2 on 2026-03-20 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myground', '0002_awsaccount_awscostanomaly_awscostsnapshot'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='awscostsnapshot',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='awscostsnapshot',
            name='aws_account',
        ),
        migrations.RemoveField(
            model_name='awsaccount',
            name='last_synced_at',
        ),
        migrations.CreateModel(
            name='AWSCostCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=100, unique=True)),
                ('cache_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('aws_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_caches', to='myground.awsaccount')),
            ],
        ),
        migrations.CreateModel(
            name='CostDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('driver_type', models.CharField(choices=[('increase', 'Cost Increase'), ('decrease', 'Cost Decrease'), ('anomaly', 'Anomaly'), ('top', 'Top Driver')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('impact_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('affected_region', models.CharField(blank=True, max_length=50)),
                ('resource_count', models.IntegerField(default=0)),
                ('sample_resources', models.JSONField(default=list)),
                ('recommendation', models.TextField(blank=True)),
                ('estimated_savings', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('aws_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_drivers', to='myground.awsaccount')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.DeleteModel(
            name='AWSCostAnomaly',
        ),
        migrations.DeleteModel(
            name='AWSCostSnapshot',
        ),
        migrations.AddIndex(
            model_name='awscostcache',
            index=models.Index(fields=['aws_account', 'cache_key'], name='myground_aw_aws_acc_ee3c7b_idx'),
        ),
        migrations.AddIndex(
            model_name='awscostcache',
            index=models.Index(fields=['expires_at'], name='myground_aw_expires_1764b3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='awscostcache',
            unique_together={('aws_account', 'cache_key')},
        ),
    ]
