# Generated by Django 6.0.2 on 2026-03-20 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myground', '0003_alter_awscostsnapshot_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWSCostAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('ai_insights', 'AI Generated Insights'), ('manual', 'Manual Analysis')], default='ai_insights', max_length=20)),
                ('analysis_data', models.JSONField(default=dict)),
                ('analysis_result', models.TextField()),
                ('cost_drivers_used', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aws_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_analyses', to='myground.awsaccount')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['aws_account', 'analysis_type', '-created_at'], name='myground_aw_aws_acc_0b64fe_idx')],
            },
        ),
    ]
