# Generated by Django 6.0.2 on 2026-03-24 21:17

import django.db.models.deletion
import myground.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myground', '0004_awscostanalysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostSpike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('increase_percentage', models.DecimalField(decimal_places=2, max_digits=6)),
                ('before_cost', models.DecimalField(decimal_places=4, max_digits=12)),
                ('after_cost', models.DecimalField(decimal_places=4, max_digits=12)),
                ('services_affected', models.JSONField(default=list)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aws_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_spikes', to='myground.awsaccount')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='GitHubRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_id', models.BigIntegerField(help_text='GitHub repository ID')),
                ('repo_name', models.CharField(max_length=255)),
                ('repo_full_name', models.CharField(max_length=255)),
                ('repo_url', models.URLField()),
                ('access_token', myground.models.EncryptedTextField(help_text='Encrypted GitHub access token')),
                ('installation_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('failed', 'Connection Failed')], default='connected', max_length=20)),
                ('webhook_id', models.BigIntegerField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aws_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='github_repos', to='myground.awsaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_repos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-connected_at'],
            },
        ),
        migrations.CreateModel(
            name='DeploymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_number', models.IntegerField()),
                ('pr_title', models.CharField(max_length=500)),
                ('pr_url', models.URLField()),
                ('merged_by', models.CharField(max_length=255)),
                ('merged_at', models.DateTimeField()),
                ('files_changed', models.JSONField(default=list, help_text='List of files modified in this PR')),
                ('services_affected', models.JSONField(default=list, help_text='AWS services that might be affected')),
                ('cost_impact', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('is_correlated', models.BooleanField(default=False)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('aws_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='myground.awsaccount')),
                ('cost_spike_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='myground.costspike')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='myground.githubrepo')),
            ],
            options={
                'ordering': ['-merged_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='githubrepo',
            constraint=models.CheckConstraint(condition=models.Q(('aws_account__isnull', False)), name='repo_must_have_aws_account'),
        ),
        migrations.AlterUniqueTogether(
            name='githubrepo',
            unique_together={('user', 'repo_id')},
        ),
        migrations.AddIndex(
            model_name='deploymentevent',
            index=models.Index(fields=['merged_at'], name='myground_de_merged__d8ee3b_idx'),
        ),
        migrations.AddIndex(
            model_name='deploymentevent',
            index=models.Index(fields=['aws_account', 'merged_at'], name='myground_de_aws_acc_9d9b97_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deploymentevent',
            unique_together={('repo', 'pr_number')},
        ),
    ]
