# Generated by Django 6.0.2 on 2026-03-26 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myground', '0006_githubuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostDataHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_type', models.CharField(choices=[('90_days', '90 Days Total'), ('monthly', 'Monthly Cost'), ('7_days', '7 Days Chart'), ('yesterday', 'Yesterday Cost'), ('low_level', 'Low Level Costs'), ('cost_drivers', 'Cost Drivers')], max_length=20)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aws_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_data_history', to='myground.awsaccount')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('aws_account', 'cost_type')},
            },
        ),
    ]
