# Generated by Django 6.0.2 on 2026-04-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myground', '0008_lowlevelservicecategory_lowlevelservicedefinition_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='githubrepo',
            name='repo_must_have_aws_account',
        ),
        migrations.AlterField(
            model_name='githubrepo',
            name='repo_url',
            field=models.URLField(max_length=500),
        ),
    ]
