# Generated by Django 6.0.2 on 2026-04-13 21:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myground', '0009_remove_githubrepo_repo_must_have_aws_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateStorageFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duplicate_type', models.CharField(choices=[('exact', 'Exact Duplicate'), ('likely', 'Likely Duplicate'), ('redundant_backup', 'Redundant Backup Candidate')], max_length=20)),
                ('group_id', models.CharField(max_length=100)),
                ('group_name', models.CharField(max_length=500)),
                ('resources', models.JSONField(default=list)),
                ('total_wasted_size_gb', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estimated_savings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reason', models.TextField()),
                ('recommendation', models.TextField()),
                ('status', models.CharField(default='active', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('aws_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_findings', to='myground.awsaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='CpuUsageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('ec2', 'EC2 Instance'), ('rds', 'RDS Instance')], max_length=20)),
                ('resource_id', models.CharField(max_length=500)),
                ('resource_name', models.CharField(blank=True, max_length=500)),
                ('region', models.CharField(max_length=50)),
                ('avg_cpu_percent', models.FloatField(default=0)),
                ('max_cpu_percent', models.FloatField(default=0)),
                ('min_cpu_percent', models.FloatField(default=0)),
                ('sample_count', models.IntegerField(default=0)),
                ('is_idle', models.BooleanField(default=False)),
                ('idle_threshold', models.FloatField(default=5.0)),
                ('recommendation', models.TextField(blank=True)),
                ('estimated_savings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('metadata', models.JSONField(default=dict)),
                ('snapshot_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aws_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpu_snapshots', to='myground.awsaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-snapshot_date'],
                'indexes': [models.Index(fields=['user', 'aws_account', 'is_idle'], name='myground_cp_user_id_eddb9c_idx'), models.Index(fields=['resource_type', 'snapshot_date'], name='myground_cp_resourc_566818_idx')],
                'unique_together': {('user', 'aws_account', 'resource_id', 'snapshot_date')},
            },
        ),
        migrations.CreateModel(
            name='ResourceUsageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(choices=[('ebs', 'EBS'), ('s3', 'S3'), ('rds', 'RDS'), ('snapshots', 'Snapshots'), ('dynamodb', 'DynamoDB')], max_length=50)),
                ('region', models.CharField(blank=True, max_length=50)),
                ('usage_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('unit', models.CharField(default='GB', max_length=20)),
                ('metadata', models.JSONField(default=dict)),
                ('snapshot_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aws_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_snapshots', to='myground.awsaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-snapshot_date'],
                'indexes': [models.Index(fields=['user', 'aws_account', 'snapshot_date'], name='myground_re_user_id_d23c12_idx'), models.Index(fields=['service_name', 'snapshot_date'], name='myground_re_service_b535b0_idx')],
                'unique_together': {('user', 'aws_account', 'service_name', 'region', 'snapshot_date')},
            },
        ),
        migrations.CreateModel(
            name='StorageOptimizationFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(choices=[('ebs_volume', 'EBS Volume'), ('elastic_ip', 'Elastic IP'), ('ebs_snapshot', 'EBS Snapshot'), ('s3_bucket', 'S3 Bucket'), ('s3_object', 'S3 Object'), ('rds_instance', 'RDS Instance'), ('rds_snapshot', 'RDS Snapshot'), ('dynamodb_table', 'DynamoDB Table'), ('unused_ami', 'Unused AMI'), ('load_balancer', 'Load Balancer')], max_length=50)),
                ('resource_id', models.CharField(max_length=500)),
                ('resource_name', models.CharField(blank=True, max_length=500)),
                ('region', models.CharField(blank=True, max_length=50)),
                ('size_gb', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estimated_monthly_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('reason', models.TextField()),
                ('recommendation', models.TextField()),
                ('severity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('ignored', 'Ignored'), ('dismissed', 'Dismissed')], default='active', max_length=20)),
                ('metadata', models.JSONField(default=dict)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('aws_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_findings', to='myground.awsaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['user', 'aws_account', 'status'], name='myground_st_user_id_2a335b_idx'), models.Index(fields=['resource_type', 'severity'], name='myground_st_resourc_b2247e_idx'), models.Index(fields=['detected_at'], name='myground_st_detecte_3eed6b_idx')],
            },
        ),
        migrations.CreateModel(
            name='StorageOptimizationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_idle_resources', models.IntegerField(default=0)),
                ('total_estimated_waste', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('duplicate_candidates', models.IntegerField(default=0)),
                ('duplicate_savings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('idle_cpu_resources', models.IntegerField(default=0)),
                ('cpu_savings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('weekly_growth_percent', models.FloatField(default=0)),
                ('monthly_growth_percent', models.FloatField(default=0)),
                ('summary_data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aws_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimization_summary', to='myground.awsaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'aws_account')},
            },
        ),
    ]
