# Generated by Django 6.0.2 on 2026-04-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myground', '0010_duplicatestoragefinding_cpuusagesnapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageoptimizationfinding',
            name='resource_type',
            field=models.CharField(choices=[('ebs_volume', 'EBS Volume'), ('elastic_ip', 'Elastic IP'), ('ebs_snapshot', 'EBS Snapshot'), ('s3_bucket', 'S3 Bucket'), ('rds_instance', 'RDS Instance'), ('rds_snapshot', 'RDS Snapshot'), ('dynamodb_table', 'DynamoDB Table'), ('unused_ami', 'Unused AMI'), ('load_balancer', 'Load Balancer')], max_length=50),
        ),
    ]
