# Generated by Django 6.0.2 on 2026-04-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myground', '0012_idleapigateway_idleautoscalinggroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awscostanalysis',
            name='analysis_type',
            field=models.CharField(choices=[('ai_insights', 'AI Generated Insights'), ('ai_low_level', 'AI Low Level Recommendations'), ('manual', 'Manual Analysis')], default='ai_insights', max_length=20),
        ),
    ]
