# Generated by Django 5.1.4 on 2026-09-21 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myground', '0013_alter_awscostanalysis_analysis_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceAIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_category', models.CharField(default='Other', max_length=100)),
                ('service_name', models.CharField(max_length=100)),
                ('resource_id', models.CharField(max_length=500)),
                ('resource_name', models.CharField(blank=True, max_length=500)),
                ('resource_type', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=50)),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('ON', 'On'), ('OFF', 'Off'), ('STOPPED', 'Stopped'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('on_since', models.DateTimeField(blank=True, null=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('cpu_avg', models.FloatField(default=0)),
                ('memory_avg', models.FloatField(blank=True, null=True)),
                ('network_in_mb', models.FloatField(default=0)),
                ('network_out_mb', models.FloatField(default=0)),
                ('disk_read_mb', models.FloatField(default=0)),
                ('disk_write_mb', models.FloatField(default=0)),
                ('monthly_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ai_verdict', models.CharField(choices=[('LEAVE_IT', 'Leave It'), ('MONITOR_IT', 'Monitor It'), ('SCHEDULE_IT', 'Schedule It'), ('DOWNSIZE_IT', 'Downsize It'), ('STOP_IT', 'Stop It'), ('TERMINATE_IT', 'Terminate It')], default='MONITOR_IT', max_length=20)),
                ('ai_short_reason', models.CharField(blank=True, max_length=500)),
                ('ai_detailed_explanation', models.TextField(blank=True)),
                ('ai_savings_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ai_savings_yearly', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ai_risk', models.CharField(choices=[('ZERO', 'Zero Risk'), ('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk')], default='LOW', max_length=20)),
                ('ai_steps', models.JSONField(blank=True, default=list)),
                ('ai_alternatives', models.JSONField(blank=True, default=list)),
                ('ai_time_to_fix', models.CharField(blank=True, max_length=100)),
                ('ai_one_click_available', models.BooleanField(default=False)),
                ('ai_priority', models.IntegerField(default=5)),
                ('resource_details', models.JSONField(blank=True, default=dict)),
                ('ai_generated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aws_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_ai_analyses', to='myground.awsaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_ai_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ai_priority', '-ai_savings_monthly'],
                'indexes': [models.Index(fields=['aws_account', 'service_name'], name='myground_re_aws_acc_babf55_idx'), models.Index(fields=['aws_account', 'ai_verdict'], name='myground_re_aws_acc_4981c4_idx'), models.Index(fields=['aws_account', 'service_category'], name='myground_re_aws_acc_ff2e81_idx')],
                'unique_together': {('aws_account', 'resource_id')},
            },
        ),
    ]
