# Generated by Django 5.1.4 on 2026-09-23 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myground', '0014_resourceaianalysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceaianalysis',
            name='region_scanned',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.CreateModel(
            name='BreakdownSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_scanned', models.CharField(db_index=True, max_length=50)),
                ('total_resources', models.IntegerField(default=0)),
                ('total_services', models.IntegerField(default=0)),
                ('total_monthly_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_savings_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_summary_data', models.JSONField(blank=True, default=dict)),
                ('scan_duration_seconds', models.FloatField(blank=True, null=True)),
                ('ai_calls_made', models.IntegerField(default=0)),
                ('ai_calls_skipped', models.IntegerField(default=0)),
                ('scanned_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aws_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdown_summaries', to='myground.awsaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdown_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['aws_account', 'region_scanned'], name='myground_br_aws_acc_a83127_idx')],
                'unique_together': {('aws_account', 'region_scanned')},
            },
        ),
    ]
