# Generated by Django 5.1.4 on 2026-09-23 15:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myground', '0015_resourceaianalysis_region_scanned_breakdownsummary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resourceaianalysis',
            unique_together={('aws_account', 'resource_id', 'region_scanned')},
        ),
        migrations.AddIndex(
            model_name='resourceaianalysis',
            index=models.Index(fields=['aws_account', 'region_scanned'], name='myground_re_aws_acc_73a250_idx'),
        ),
    ]
