# Generated by Django 5.1.4 on 2026-09-26 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myground', '0016_alter_resourceaianalysis_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_scanned', models.CharField(db_index=True, max_length=50)),
                ('tomorrow_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('next_month_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('three_month_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_monthly_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('resource_count', models.IntegerField(default=0)),
                ('top_resources', models.JSONField(blank=True, default=list)),
                ('ai_summary', models.TextField(blank=True)),
                ('scanned_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aws_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_forecasts', to='myground.awsaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_forecasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['aws_account', 'region_scanned'], name='myground_re_aws_acc_fee4b5_idx')],
                'unique_together': {('aws_account', 'region_scanned')},
            },
        ),
    ]
