# Generated by Django 5.1.4 on 2026-09-30 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myground', '0017_resourceforecast'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdleScanError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detector', models.CharField(db_index=True, max_length=50)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.TextField(blank=True)),
                ('missing_permission', models.CharField(blank=True, max_length=200)),
                ('required_iam_action', models.TextField(blank=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aws_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idle_scan_errors', to='myground.awsaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idle_scan_errors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['aws_account', 'detector'], name='myground_id_aws_acc_7aead4_idx'), models.Index(fields=['aws_account', 'is_acknowledged'], name='myground_id_aws_acc_48227f_idx')],
                'unique_together': {('aws_account', 'detector', 'missing_permission')},
            },
        ),
    ]
