# Generated by Django 6.0.2 on 2026-05-07 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myground', '0013_alter_awscostanalysis_analysis_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IAMFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_type', models.CharField(choices=[('admin_user', 'Administrative User'), ('wildcard_role', 'Wildcard Role'), ('unused_user', 'Unused User'), ('old_key', 'Old Access Key'), ('multiple_keys', 'Multiple Active Keys'), ('no_mfa', 'No MFA Enabled')], max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=20)),
                ('resource_name', models.CharField(blank=True, help_text='Name of the IAM user/role', max_length=255)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('recommendation', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('aws_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iam_findings', to='myground.awsaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iam_findings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['aws_account', 'severity'], name='security_ia_aws_acc_3e68e3_idx'), models.Index(fields=['aws_account', 'is_resolved'], name='security_ia_aws_acc_56e442_idx')],
            },
        ),
    ]
